### ISSUE TITLE
UART emulation?

### ISSUE THREAD

**Issue by majenkotech** [fdivitto/FabGL#213]
Do you have plans to create an emudev for the 16550 (or 16450, or even 8250) UART? This would massively enhance the PCEmulator and allow it to actually communicate with the outside world. It would be useful too if it were possible to choose where the serial connects to (physical UART, or a TCP socket, ideally with `ttynvt` compatibility).

**Comment by fdivitto** [comment]
I'm working on 16450 and 8250 emulation (no FIFO). There are already some commits, so you can test it.

Something still doesn't work: for example I'd like to run LAPLINK to transfer files from PC to ESP32-PC, but I still can't do it!

At the moment the emulated UART is connected to USB serial connection.

**Comment by majenkotech** [comment]
Awesome. Right now I am transferring msdos kermit zip file using xmodem in the windows 3 terminal at 9600 baud :)

**Comment by fishhack66** [comment]
> Awesome. Right now I am transferring msdos kermit zip file using xmodem in the windows 3 terminal at 9600 baud :)

Hi guys.  Majen - could you send me a PM; I have some questions about establishing connection via the Windows 3.0 Terminal (mainly to do with hardware cabling...need a null modem, some USB size adapters??), and I don't want to bog down this issue thread.  Thanks, Dave

**Comment by majenkotech** [comment]
Incidentally, the best way I have found of transferring files so far is using XModem with Procomm on the DOS side and Minicom on the Linux side. I'm just in the process of seeing if it's possible to use epppd and mTCP to connect DOS to the network :)

**Comment by fdivitto** [comment]
There is a free and nice tool I'm using on both sides (real PC and ESP32 emulated), to transfer files, using a UI like laplink. It is File Maven:

http://www.briggsoft.com/fmdos.htm

If you run it on an emulated PC (like dosbox) you should slow down it to 8Mhz otherwise it could not reliability  communicate.

Of course there other ways: I like for example c-kermit, which runs on almost all OS and platforms (included CP/M).
